# Generated by Django 4.2 on 2023-05-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('age', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'm'), ('female', 'f')], max_length=10)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('autre', 'autre')], max_length=10)),
                ('blood_donation', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=10)),
                ('second_question', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=10)),
                ('third_question', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=10)),
                ('fourth_question', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=10)),
                ('fifth_question', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=10)),
                ('sixth_question', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=10)),
                ('seventh_question', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=10)),
            ],
        ),
    ]
